# HOUSING PRICE PREDICTION ML MODEL

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('HousePricePrediction.csv')
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
df['SalePrice'].isnull().sum()

np.int64(1459)

In [6]:
df['SalePrice'].nunique()

663

In [7]:
df['MSZoning'].isnull().sum()

np.int64(4)

In [8]:
df = df.dropna(subset=['SalePrice'])

In [9]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,60,RL,7917,Inside,1Fam,5,1999,2000,VinylSd,0.0,953.0,175000.0
1456,1456,20,RL,13175,Inside,1Fam,6,1978,1988,Plywood,163.0,1542.0,210000.0
1457,1457,70,RL,9042,Inside,1Fam,9,1941,2006,CemntBd,0.0,1152.0,266500.0
1458,1458,20,RL,9717,Inside,1Fam,6,1950,1996,MetalSd,1029.0,1078.0,142125.0
1459,1459,20,RL,9937,Inside,1Fam,6,1965,1965,HdBoard,290.0,1256.0,147500.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 0 to 1459
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            1460 non-null   int64
 1   MSSubClass    1460 non-null   int64
 2   MSZoning      1460 non-null   object
 3   LotArea       1460 non-null   int64
 4   LotConfig     1460 non-null   object
 5   BldgType      1460 non-null   object
 6   OverallCond   1460 non-null   int64
 7   YearBuilt     1460 non-null   int64
 8   YearRemodAdd  1460 non-null   int64
 9   Exterior1st   1460 non-null   object
 10  BsmtFinSF2    1460 non-null   float64
 11  TotalBsmtSF   1460 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 159.7+ KB

In [11]:
std_lot_area = StandardScaler()
std_year_built = StandardScaler()
std_year_remod = StandardScaler()

In [12]:
df['LotArea'] = std_lot_area.fit_transform(df[['LotArea']])
df['YearBuilt'] = std_year_built.fit_transform(df[['YearBuilt']])
df['YearRemodAdd'] = std_year_remod.fit_transform(df[['YearRemodAdd']])

C:\Users\WELCOME\AppData\Local\Temp\ipykernel_7512\3950830325.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['LotArea'] = std_lot_area.fit_transform(df[['LotArea']])
C:\Users\WELCOME\AppData\Local\Temp\ipykernel_7512\3950830325.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['YearBuilt'] = std_year_built.fit_transform(df[['YearBuilt']])
C:\Users\WELCOME\AppData\Local\Temp\ipykernel_7512\3950830325.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['YearRemodAdd'] = std_year_remod.fit_transform(df[['YearRemodAdd']])

In [13]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,-0.207142,Inside,1Fam,5,1.050994,0.878668,VinylSd,0.0,856.0,208500.0
1,1,20,RL,-0.091886,FR2,1Fam,8,0.156734,-0.429577,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,0.073480,Inside,1Fam,5,0.984752,0.830215,VinylSd,0.0,920.0,223500.0
3,3,70,RL,-0.096897,Corner,1Fam,5,-1.863632,-0.720298,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,0.375148,FR2,1Fam,5,0.951632,0.733308,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,60,RL,-0.260560,Inside,1Fam,5,0.918511,0.733308,VinylSd,0.0,953.0,175000.0
1456,1456,20,RL,0.266407,Inside,1Fam,6,0.222975,0.151865,Plywood,163.0,1542.0,210000.0
1457,1457,70,RL,-0.147810,Inside,1Fam,9,-1.002492,1.024029,CemntBd,0.0,1152.0,266500.0
1458,1458,20,RL,-0.080160,Inside,1Fam,6,-0.704406,0.539493,MetalSd,1029.0,1078.0,142125.0
1459,1459,20,RL,-0.058112,Inside,1Fam,6,-0.207594,-0.962566,HdBoard,290.0,1256.0,147500.0

In [14]:
df['LotConfig'].unique()

array(['Inside', 'FR2', 'Corner', 'CulDSac', 'FR3'], dtype=object)

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
df['BldgType'].unique()

array(['1Fam', '2fmCon', 'Duplex', 'TwnhsE', 'Twnhs'], dtype=object)

In [17]:
df['MSZoning'].unique()

array(['RL', 'RM', 'C (all)', 'FV', 'RH'], dtype=object)

In [18]:
std_ttl_bsmt_sf = StandardScaler()
df['TotalBsmtSF'] = std_ttl_bsmt_sf.fit_transform(df[['TotalBsmtSF']])

C:\Users\WELCOME\AppData\Local\Temp\ipykernel_7512\2153451303.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TotalBsmtSF'] = std_ttl_bsmt_sf.fit_transform(df[['TotalBsmtSF']])

In [19]:
from sklearn.preprocessing import LabelEncoder
mszoning_enco = LabelEncoder()
bldg_type_enco = LabelEncoder()
lot_config_enco = LabelEncoder()
df['MSZoning_enco'] = mszoning_enco.fit_transform(df['MSZoning'])
df['BldgType_enco'] = bldg_type_enco.fit_transform(df['BldgType'])
df['LotConfig_enco'] = lot_config_enco.fit_transform(df['LotConfig'])

C:\Users\WELCOME\AppData\Local\Temp\ipykernel_7512\1792135038.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['MSZoning_enco'] = mszoning_enco.fit_transform(df['MSZoning'])
C:\Users\WELCOME\AppData\Local\Temp\ipykernel_7512\1792135038.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BldgType_enco'] = bldg_type_enco.fit_transform(df['BldgType'])
C:\Users\WELCOME\AppData\Local\Temp\ipykernel_7512\1792135038.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['LotConfig_enco'] = lot_config_enco.fit_transform(df['LotConfig'])

In [21]:

df[['LotConfig','LotConfig_enco']].drop_duplicates()

    LotConfig  LotConfig_enco
0      Inside               4
1         FR2               2
3      Corner               0
16    CulDSac               1
333       FR3               3

In [22]:
df[['MSZoning','MSZoning_enco']].drop_duplicates()

    MSZoning  MSZoning_enco
0         RL              3
8         RM              4
30   C (all)              0
47        FV              1
341       RH              2

In [23]:
df[['BldgType','BldgType_enco']].drop_duplicates()

   BldgType  BldgType_enco
0      1Fam              0
9    2fmCon              1
17   Duplex              2
23   TwnhsE              4
56    Twnhs              3

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 0 to 1459
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              1460 non-null   int64
 1   MSSubClass      1460 non-null   int64
 2   MSZoning        1460 non-null   object
 3   LotArea         1460 non-null   float64
 4   LotConfig       1460 non-null   object
 5   BldgType        1460 non-null   object
 6   OverallCond     1460 non-null   int64
 7   YearBuilt       1460 non-null   float64
 8   YearRemodAdd    1460 non-null   float64
 9   Exterior1st     1460 non-null   object
 10  BsmtFinSF2      1460 non-null   float64
 11  TotalBsmtSF     1460 non-null   float64
 12  SalePrice       1460 non-null   float64
 13  MSZoning_enco   1460 non-null   int64
 14  BldgType_enco   1460 non-null   int64
 15  LotConfig_enco  1460 non-null   int64
dtypes: float64(6), int64(6), object(4)
memory usage: 193.9+ KB

In [28]:
features = [
    'MSSubClass',
    'MSZoning_enco',
    'LotArea',
    'LotConfig_enco',
    'BldgType_enco',
    'OverallCond',
    'YearBuilt',
    'YearRemodAdd',
    'TotalBsmtSF'   
]

In [26]:
y_true = df['SalePrice']

In [29]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
X = df[features]

In [30]:
model.fit(X,y_true)

LinearRegression()

In [31]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_enco,BldgType_enco,LotConfig_enco
0,0,60,RL,-0.207142,Inside,1Fam,5,1.050994,0.878668,VinylSd,0.0,-0.459303,208500.0,3,0,4
1,1,20,RL,-0.091886,FR2,1Fam,8,0.156734,-0.429577,MetalSd,0.0,0.466465,181500.0,3,0,2
2,2,60,RL,0.073480,Inside,1Fam,5,0.984752,0.830215,VinylSd,0.0,-0.313369,223500.0,3,0,4
3,3,70,RL,-0.096897,Corner,1Fam,5,-1.863632,-0.720298,Wd Sdng,0.0,-0.687324,140000.0,3,0,0
4,4,60,RL,0.375148,FR2,1Fam,5,0.951632,0.733308,VinylSd,0.0,0.199680,250000.0,3,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,60,RL,-0.260560,Inside,1Fam,5,0.918511,0.733308,VinylSd,0.0,-0.238122,175000.0,3,0,4
1456,1456,20,RL,0.266407,Inside,1Fam,6,0.222975,0.151865,Plywood,163.0,1.104925,210000.0,3,0,4
1457,1457,70,RL,-0.147810,Inside,1Fam,9,-1.002492,1.024029,CemntBd,0.0,0.215641,266500.0,3,0,4
1458,1458,20,RL,-0.080160,Inside,1Fam,6,-0.704406,0.539493,MetalSd,1029.0,0.046905,142125.0,3,0,4
1459,1459,20,RL,-0.058112,Inside,1Fam,6,-0.207594,-0.962566,HdBoard,290.0,0.452784,147500.0,3,0,4

In [35]:
mssubclass = int(input('enter the mssubclass: '))
mszoning = int(input('''enter the ms zoning 
                     guide is as follows
                     1. RL:3
                     2. RM:4
                     3. C(all): 0
                     4. FV : 1
                     5. RH : 2
                     enter the encoded one: '''))
lotarea = float(input('enter the lot area: '))
lotarea = std_lot_area.transform([[lotarea]])[0][0]
lotconfig = int(input('''enter the lot config
                      lot config are as follows:
                      1. Inside: 4
                      2. Corner : 0
                      3. FR2: 2
                      4. FR3: 3
                      5. CulDSac: 1
                      enter the encoded one: '''))
blgdtype = int(input('''enter the building type
                     building type are as follows 
                     1. 1Fam : 0
                     2. Duplex : 2
                     3. 2fmCon: 1
                     4. Twnhs: 3
                     5. TwnhsE: 4'''))
overallcond = int(input('enter the overall cond: '))
year_built = int(input('enter the year of built: '))
year_built = std_year_built.transform([[year_built]])[0][0]
year_remodadd = float(input('enter the year of remodadd: '))
year_remodadd = std_year_remod.transform([[year_remodadd]])[0][0]
total_bsmtsf = float(input('enter the total bsmt sf: '))
total_bsmtsf = std_ttl_bsmt_sf.transform([[total_bsmtsf]])[0][0]
input_features = [
    mssubclass,
    mszoning,
    lotarea,
    lotconfig,
    blgdtype,
    overallcond,
    year_built,
    year_remodadd,
    total_bsmtsf,
]
answer = model.predict([input_features])[0]
answer

c:\Users\WELCOME\miniconda3\envs\torch_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\WELCOME\miniconda3\envs\torch_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\WELCOME\miniconda3\envs\torch_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\WELCOME\miniconda3\envs\torch_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\WELCOME\miniconda3\envs\torch_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

np.float64(229336.84016640286)

In [37]:
from sklearn.metrics import r2_score
y_pred = model.predict(df[features])

In [ ]:
r2_score = r2_score(y_true,y_pred)
r2_score

0.5772596582993937